### PR TITLE
Add a useful option from obsidian

### PR DESCRIPTION
**Pull request by SpyrosMourelatos**
In the `.obsidian/app.json` file there is a setting about the default directory for new pages, by default it is empty (so obsidian creates the files on the root of the project) but it can get non default values like:
`"newFileFolderPath": "pages"`. This PR is reading this value from the JSON and if it doesn't exist it keeps the default behavior. If the value exists, it respects it on the code action about creating new files. I tested it with some simple cases and it works just fine.
PS1:Maybe we need to add some documentation about that as you provide for the rest of the options
PS2:I also added a commit that cleans up most of the existing warnings,(I didn't introduce any new) except two that I am unsure about how to handle.

### CODE REVIEW

**Comment by Feel-ix-343** [comment]
Oooh great! I will review soon

Maybe we could pick up #56 too. By default the root dir can be this setting, but we can make an override too.

**Comment by Feel-ix-343** [comment]
I love the thought to read from Obsidian's settings for this

**Comment by Feel-ix-343** [comment]
And there is documentation for the config file in the readme; under the config or settings heading. 

Perhaps a table of contents would help make this more visible.

Also I am planning to make a website/wiki for this in the future #84

**Comment by SpyrosMourelatos** [comment]
Hey I added the idea noted on https://github.com/Feel-ix-343/markdown-oxide/issues/56 , unfortunatelly I haven't tested it because I don't use this lsp for auto completion. Although I believe it is very importan to integrate this feature mentioned on #56 because with this two additions I would say that the project fully supports logseq! This statement seems a bit out of the blue but let me explain myself with this small section of a video. https://youtu.be/knxDHO3U2_8?t=98

**Comment by Feel-ix-343** [comment]
:open_mouth: Thank you! This is so great and exciting

**Comment by Feel-ix-343** [comment]
> the project fully supports logseq

I think this is a great step in that direction. 

I would say one more thing to implement is the `(())` block linking syntax.

**Comment by Feel-ix-343** [comment]
shoot

**Comment by Feel-ix-343** [comment]
open

**Pull request closed without merging**
